[package]
name = "fuzzpaint-types"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = {version = "0.22.1", default-features = false }
bitflags = { version = "2.10.0", features = ["bytemuck"] }
crc = "3.4.0"
either = "1.15.0"

bytemuck = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
ultraviolet = { workspace = true }