[package]
name = "fuzzpaint-vk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
bitvec = "1.0.1"
bytemuck = "1.13.1"
cgmath = "0.18.0"
egui = {version = "0.22.0", features = ["bytemuck"]}
env_logger = "0.10.0"
image = "0.24.6"
log = "0.4.18"
parking_lot = "0.12.1"
rand = {version = "0.8.5", features = ["small_rng"]}
rfd = "0.11.4"
smallvec = "1.10.0"
strum = {version = "0.25.0", features = ["derive"]}
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["sync", "rt"] }
try-block = "0.1.0"
uuid = { version = "1.4.0", features = ["v4"] }
vulkano = "0.33.0"
vulkano-shaders = "0.33.0"
vulkano-win = "0.33.0"
winit = "0.28.6"

[profile.profiling]
inherits = "release"
debug = true
