[package]
name = "fuzzpaint-vk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
bytemuck = "1.13.1"
cgmath = "0.18.0"
egui = {version = "0.22.0", features = ["bytemuck"]}
image = "0.24.6"
smallvec = "1.10.0"
try-block = "0.1.0"
vulkano = "0.33.0"
vulkano-shaders = "0.33.0"
vulkano-win = "0.33.0"
winit = "0.28.6"
