/// Requests generated by the user interface.
#[derive(Debug)]
pub enum UiRequest {
    Document {
        target: crate::state::DocumentID,
        request: DocumentRequest,
    },
    SetBaseTool {
        tool: crate::pen_tools::StateLayer,
    },
}
/// Requests that apply to a specific layer of a specific document
#[derive(Debug)]
pub enum NodeRequest {
    /// This layer is now focused. For now, focus is a unique role, thus all other
    /// layers are to be unfocused when this request is acknowledged.
    Focus,
    /// A partial change to the layer's blend. Reported during editting to give the user
    /// visual feedback, prior to finalizing the blend and sending it to the queue. Not all
    /// blend changes will be reported via this request!
    InProgressBlend(crate::blend::Blend),
}
#[derive(Debug)]
pub enum DocumentViewRequest {
    Fit,
    /// Set the absolute scale. One document pixel = this many screen pixels.
    RealSize(f32),
    /// Set the absolute rotation, in radians CCW.
    SetRotation(f32),
}
/// Request that applies to a specific document
#[derive(Debug)]
pub enum DocumentRequest {
    Node {
        // Todo: other kinds of layer.
        target: crate::state::graph::AnyID,
        request: NodeRequest,
    },
    View(DocumentViewRequest),
    /// This document is now focused. For now, focus is a unique role, thus all other
    /// documents are to be unfocused when this request is acknowledged.
    Focus,
    /// UI caused this document to be created. Via from a file open, open as new, or new.
    Opened,
    Close,
    /// Save the document in-place
    Save,
    /// Save the document to the given path
    SaveCopy(std::path::PathBuf),
}
