[package]
name = "fuzzpaint-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.100"
az = "1.2.1"
base64 = {version = "0.22.1", default-features = false }
bitflags = { version = "2.10.0", features = ["bytemuck"] }
bitvec = { version = "1.0.1", default-features = false, features = [
    "alloc",
    "std",
] }
blake3 = "1.8.2"
bytemuck = { version = "1.24.0", features = ["derive"] }
chrono = { version = "0.4.42", default-features = false }
crc = "3.4.0"
dirs = "5.0.1"
either = "1.15.0"
fontdb = "0.16.2"
hashbrown = { version = "0.14.5", features = ["serde"] }
human_bytes = "0.4.3"
id_tree = "1.8.0"
log = "0.4.29"
parking_lot = "0.12.5"
rangemap = "1.7.0"
rustybuzz = "0.13.0"
slab_tree = "0.3.2"
smallvec = { version = "1.15.1", features = ["serde", "union"] }
strum = { version = "0.26.3", features = ["derive"] }
thiserror = "1.0.69"
unicode-segmentation = "1.12.0"
uuid = { version = "1.19.0", features = ["v4"] }
