[package]
name = "fuzzpaint-connection"
version = "0.1.0"
edition = "2024"

[dependencies]
fuzzpaint-collections = { path = "../fuzzpaint-collections" }
fuzzpaint-types = { path = "../fuzzpaint-types" }
bitcode = "0.6.9"
log = "0.4.29"
# Tokio is smoller than smol (probably cuz more eyes on it to optimize)
# It has a worse (more-implicit) API tho :V
tokio = { version = "1.49.0", optional = true }

[features]
default = ["client", "server", "tcp"]
client = []
server = []

# TCP-based connection.
tcp = ["dep:tokio", "tokio/net", "tokio/io-util"]

# A channel-based connection for a server and client within the same process.
# inprocess = ["dep:tokio", "tokio/sync"]

# An interprocess-channel-based connection, using unidirectional shared mem to
# share blobs in an insulated manner.
# ipc-shm = []

[dev-dependencies]
# Needs a runtime and `join` for some tests.
tokio = { version = "1.49.0", features = ["rt", "macros"] }
